<?php

namespace AppBundle\Repository;

/**
 * ArtworkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtworkRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBestArtwork()
    {
        $qb = $this->createQueryBuilder('a')
            ->select('a')
            ->where('g.score = :max')
            ->setParameter(':max', 4)
            ->getQuery()
            ->getResult();
        return $qb;
    }
}
