<?php

namespace AppBundle\Repository;

/**
 * SharingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SharingRepository extends \Doctrine\ORM\EntityRepository
{
}
