chat_room:
    resource: "@ChatBundle/Controller/RoomController.php"
    type:     annotation

app:
    resource: "@AppBundle/Resources/config/routing.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

chat:
    resource: "@ChatBundle/Resources/config/routing.yml"