design_index:
    path:     /
    defaults: { _controller: "AppBundle:Design:index" }
    methods:  GET

design_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Design:show" }
    methods:  GET

design_new:
    path:     /new
    defaults: { _controller: "AppBundle:Design:new" }
    methods:  [GET, POST]

design_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Design:edit" }
    methods:  [GET, POST]

design_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Design:delete" }
    methods:  DELETE
