services:
#    app.voter:
#        class: AppBundle\Service\Voter
#        arguments: [%template_path%, %new_game_path%, %web_path%]

    app.cover.namer:
        class: AppBundle\Service\CoverImageNamer
        tags:
            - { name: namer }
