services:
#    app.voter:
#        class: AppBundle\Service\Voter
#        arguments: [%template_path%, %new_game_path%, %web_path%]

    app.mail.sender:
        class: AppBundle\Service\MailSender

    app.cover.namer:
        class: AppBundle\Service\CoverImageNamer
        tags:
            - { name: namer }

    app.salon.maker:
        class: AppBundle\Service\SalonMaker
        tags:
            - { name: gos_web_socket.topic }