room_index:
    path:     /rooms
    defaults: { _controller: "ChatBundle:Room:index" }
    methods:  GET

room_show:
    path:     /room/{id}/show
    defaults: { _controller: "ChatBundle:Room:show" }
    methods:  GET

room_new:
    path:     /room/new
    defaults: { _controller: "ChatBundle:Room:new" }
    methods:  [GET, POST]

room_edit:
    path:     /room/{id}/edit
    defaults: { _controller: "ChatBundle:Room:edit" }
    methods:  [GET, POST]

room_delete:
    path:     /room/{id}/delete
    defaults: { _controller: "ChatBundle:Room:delete" }
    methods:  DELETE
